# -*- coding: utf-8 -*-
"""Yolo V5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XB6RCP80cPxEcr9-Sdu-obGbwaJyXw-p
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5  # clone repo
# %cd yolov5
# %pip install -qr requirements.txt # install dependencies
# %pip install -q roboflow

import torch

import os
from IPython.display import Image, clear_output  # to display images

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

!python train.py --img 416 --batch 16 --epochs 50 --data  /content/yolov5/data/coco.yaml --weights yolov5s.pt --cache

!python detect.py --weights runs/train/exp3/weights/best.pt --img 416 --conf 0.5 --source /content/drive/MyDrive/Neetiraj_Assignment/Dataset/test/images

import glob
from IPython.display import Image, display

for imageName in glob.glob('/content/yolov5/runs/detect/exp/*.jpg'): #assuming JPG
    display(Image(filename=imageName))
    print("\n")

from IPython.display import Image

Image('/content/yolov5/runs/train/exp3/F1_curve.png')

